// =====================================================================
// Serve the public site.
//
//   node site.native.mjs <site dir> <http port> [https port] [tls dir]
//
// WHY THIS IS A SEPARATE FILE FROM web.native.mjs
//
// That one proxies /api/ and /healthz to the service on 8090, because
// the portal and the console need the page and its API on one origin.
// This one must NOT, and the difference is the whole point.
//
// The site is the one surface here meant to be published. Serving it
// with a program that also forwards /api/ would publish the API along
// with it - including /api/v1/auth, on a service running OTP_ECHO=true,
// which returns the login code in the response body. Anyone who knew a
// parent's mobile number would sign in as that parent and read a
// child's clinical record. Nobody would have decided to publish the
// API; it would have arrived attached to the marketing page.
//
// So there is no proxy in this file at all, and adding one back is not
// a refactor - it is a decision to publish the service.
//
// The second difference is smaller and still worth keeping: an unknown
// path here returns 404, not index.html. This is a set of pages, not a
// single-page application, and answering every typo with the home page
// hides broken links from anyone testing them.
// =====================================================================
import http from 'node:http';
import https from 'node:https';
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(process.argv[2] ?? '.');
const PORT = Number(process.argv[3] ?? 8093);
const TLS_PORT = Number(process.argv[4] ?? 0);
const TLS_DIR = process.argv[5] ?? '';

// Public is the default here, unlike everywhere else in this deploy
// directory, and that is deliberate rather than an oversight: a
// marketing page nobody outside can reach is not doing its job. What
// makes it safe is above - this program has no route to the API and no
// route to the database, and every byte under ROOT is written to be
// read by strangers.
//
// Set HBH_SITE_BIND=127.0.0.1 to keep it on loopback while working.
const BIND = process.env.HBH_SITE_BIND || '0.0.0.0';

const TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.txt': 'text/plain; charset=utf-8',
  // hbh.site_team_media.kind is VIDEO or PHOTO, and there is a VIDEO row
  // in the table today pointing at an .mp4 in site/assets. It is still a
  // draft, so nothing on the page asks for it yet - which is exactly how
  // an allow list turns into a trap: the day somebody publishes that row
  // from the console the page would ask for a file this server refuses,
  // and the only symptom would be a member's video that does not play.
  // These two are here because the site already has the feature.
  '.mp4': 'video/mp4',
  '.webm': 'video/webm',
};

// config.js carries the deployment's portal URL and the centre's phone
// number. It is rewritten per environment and keeps its name, so a
// cached copy is a page pointing at the previous portal. The images and
// the stylesheet keep their names too, so they revalidate rather than
// being stored for a year - this site has no hashed filenames at all,
// which is the price of not having a build step.
function cacheControl(file) {
  const base = path.basename(file);
  // content.js joins config.js for the same reason: it is generated by
  // scripts/site-export.sh and keeps its name across deployments, so a
  // cached copy is a site quietly serving the previous release's phone
  // number, questions and team - with no error anywhere to notice.
  if (base === 'config.js' || base === 'content.js' || base.endsWith('.html')) return 'no-store';
  return 'no-cache';
}

function send(res, status, body, type) {
  res.writeHead(status, { 'content-type': type ?? 'text/plain; charset=utf-8' });
  res.end(body);
}

// A FILE WITH NO TYPE IN THE TABLE ABOVE IS NOT SERVED, and this is a
// rule about what the folder is, not about MIME.
//
// The handler resolves any path under ROOT and sent whatever it found,
// falling back to application/octet-stream for an extension it did not
// know. That fallback is what published site/README.md and
// site/CONTENT-AUDIT.md - two documents that sit next to the page
// because they document it, and that between them name every table
// behind the site, the permission that gates publishing, the migration
// numbers, which console screens are broken, and which testimonials are
// unpublished for want of a family's consent. `curl .../CONTENT-AUDIT.md`
// returned all of it with a 200.
//
// Nothing linked to them. That is not a control: a folder listing is not
// needed to guess README.md, and both names are ordinary.
//
// The allow list is the TYPES table itself, so adding a servable kind of
// file is one entry in one place and forgetting to is a 404 rather than
// a quiet publication. THE TEST IS THE ONE THE DEPLOY LESSON ALREADY
// NAMES: ask for what must not be answered. site.native.sh audit does.
function servable(file) {
  return Object.prototype.hasOwnProperty.call(TYPES, path.extname(file).toLowerCase());
}

function sendFile(res, file) {
  if (!servable(file)) return send(res, 404, 'not found');
  res.writeHead(200, {
    'content-type': TYPES[path.extname(file).toLowerCase()],
    'cache-control': cacheControl(file),
    // The page loads nothing of its own from anywhere but Google Fonts.
    // Stating that here means an injected <script src> from a CDN does
    // not run, whatever put it in the markup.
    'content-security-policy': [
      "default-src 'self'",
      "script-src 'self'",
      "style-src 'self' https://fonts.googleapis.com",
      "font-src https://fonts.gstatic.com",
      "img-src 'self' data: https://tile.openstreetmap.org",
      // No embedded third-party documents; the map uses image tiles.
      "frame-src 'none'",
      "frame-ancestors 'none'",
      "form-action 'none'",
    ].join('; '),
    'x-content-type-options': 'nosniff',
    'referrer-policy': 'strict-origin-when-cross-origin',
  });
  fs.createReadStream(file).pipe(res);
}

function handler(req, res) {
  if (req.method !== 'GET' && req.method !== 'HEAD') {
    return send(res, 405, 'method not allowed');
  }

  const url = (req.url ?? '/').split('?')[0];

  // Resolve inside ROOT and check it stayed there: a request for
  // ../../.env is otherwise a request this happily answers.
  let target;
  try {
    target = path.resolve(ROOT, '.' + decodeURIComponent(url));
  } catch {
    return send(res, 400, 'bad request');
  }
  if (target !== ROOT && !target.startsWith(ROOT + path.sep)) {
    return send(res, 403, 'forbidden');
  }

  fs.stat(target, (err, st) => {
    if (!err && st.isDirectory()) {
      const index = path.join(target, 'index.html');
      return fs.stat(index, (e) => (e ? send(res, 404, 'not found') : sendFile(res, index)));
    }
    if (!err && st.isFile()) return sendFile(res, target);

    // /privacy also finds privacy.html, so the footer link can be
    // written without the extension if anyone prefers it that way.
    const withHtml = target + '.html';
    fs.stat(withHtml, (e2, s2) => {
      if (!e2 && s2.isFile()) return sendFile(res, withHtml);
      send(res, 404, 'not found');
    });
  });
}

http.createServer(handler).listen(PORT, BIND, () => {
  console.log(`site http ${BIND}:${PORT} ${ROOT}  (no api proxy)`);
});

if (TLS_PORT > 0 && TLS_DIR) {
  const cert = fs.readFileSync(path.join(TLS_DIR, 'cert.pem'));
  const key = fs.readFileSync(path.join(TLS_DIR, 'key.pem'));
  https.createServer({ cert, key }, handler).listen(TLS_PORT, '0.0.0.0', () => {
    console.log(`site https 0.0.0.0:${TLS_PORT} ${ROOT}`);
  });
}
