import {Component,inject,signal,DestroyRef} from '@angular/core';
import {interval,forkJoin,of,map,catchError} from 'rxjs';
import {HttpClient,HttpParams} from '@angular/common/http';
import {takeUntilDestroyed} from '@angular/core/rxjs-interop';
import {HBH_CONFIG} from '../config/app-config';
import {FormatService} from '../format/format.service';
interface Contact{guardian_id:number;name:string;can_send:boolean;last_message?:string;last_at?:string;unread:number;can_manage:boolean}
interface Message{message_id:number;body:string;mine:boolean;created_at:string}
@Component({selector:'hbh-family-messages',template: `
<div class="comms" dir="rtl"><header><h1>التواصل مع الأسرة</h1><p>رسائل داخل النظام بين ولي الأمر وفريق المركز</p></header>
@if(contacts().some(canManage)){<button type="button" (click)="bulk.set(!bulk())" [disabled]="sending()">{{bulk()?'إغلاق الرسالة الجماعية':'رسالة جماعية'}}</button>}
@if(bulk()){<section class="bulk"><h2>رسالة للأسر المحددة</h2><p>حدد المستلمين من نتائج البحث الحالية. الإرسال يتم داخل البوابة.</p>
@for(c of contacts();track c.guardian_id){@if(c.can_send){<label><input type="checkbox" [disabled]="sending()" [checked]="recipients().includes(c.guardian_id)" (change)="toggleRecipient(c.guardian_id)">{{c.name}}</label>}}
<textarea aria-label="نص الرسالة الجماعية" rows="3" maxlength="4000" [disabled]="sending()" [value]="bulkBody()" (input)="bulkBody.set($any($event.target).value)"></textarea>
<p>{{recipients().length}} مستلم</p><button type="button" [disabled]="sending()||!recipients().length||!bulkBody().trim()" (click)="sendBulk()">إرسال إلى الأسر المحددة</button><p role="status">{{bulkStatus()}}</p></section>}
<div class="comms-grid"><aside><form (submit)="$event.preventDefault();search()"><label for="family-search">البحث بالاسم أو الجوال</label><div class="search"><input id="family-search" type="search" [value]="query()" (input)="query.set($any($event.target).value)" maxlength="100"><button type="submit">بحث</button></div></form>
@if(contactsLoading()){<p>جارٍ تحميل الأسر…</p>} @else { @for(contact of contacts();track contact.guardian_id){<button class="contact" type="button" [class.selected]="selected()?.guardian_id===contact.guardian_id" [disabled]="sending()" (click)="select(contact)">{{contact.name}} @if(contact.unread){<b class="unread">{{contact.unread}}</b>}<small>{{contact.last_message || (contact.can_send?'فتح المحادثة':'ليس لديه حساب بوابة')}}</small>@if(contact.last_at){<small>{{format.shortDate(contact.last_at)}} {{format.time(contact.last_at)}}</small>}</button>} @empty {<p>لا توجد أسر مطابقة.</p>}}
@if(moreContacts()){<p>توجد نتائج إضافية؛ حدّد الاسم أو رقم الجوال للبحث.</p>}
</aside><section class="conversation">
@if(selected();as contact){<header><h2>{{contact.name}}</h2><button type="button" (click)="load()" [disabled]="loading() || sending()">تحديث الرسائل</button></header>
@if(loading()){<p>جارٍ تحميل الرسائل…</p>}
<div class="messages" aria-live="polite">
@if(more()){<button type="button" [disabled]="loading()" (click)="load(true)">رسائل أقدم</button>}
@for(message of messages();track message.message_id){<article [class.mine]="message.mine"><small>{{message.mine?'أنت':'الطرف الآخر'}} · {{format.shortDate(message.created_at)}} {{format.time(message.created_at)}}</small><p>{{message.body}}</p></article>} @empty { @if(!loading()){<p>لا توجد رسائل بعد.</p>} }
</div>
@if(contact.can_send){<form class="compose" (submit)="$event.preventDefault();send()"><label for="message-body">الرسالة</label>@if(contact.can_manage){<select aria-label="قالب رسالة" [disabled]="sending()" (change)="useTemplate($any($event.target).value);$any($event.target).value='' "><option value="">إدراج قالب رسالة…</option>@for(t of templates;track t.title){<option [value]="t.body">{{t.title}}</option>}</select>}<textarea id="message-body" rows="3" maxlength="4000" [disabled]="sending()" [value]="draft()" (input)="draft.set($any($event.target).value)"></textarea><div><small>{{draft().length}} / 4000</small><button type="submit" [disabled]="sending() || !draft().trim()">{{sending()?'جارٍ الإرسال…':'إرسال'}}</button></div></form>} @else {<p>إرسال الرسائل متاح بعد ربط ولي الأمر بحساب البوابة.</p>}
} @else {<p class="empty">اختر أسرة لعرض المحادثة.</p>}
@if(error()){<p role="alert" class="error">{{error()}}</p>}
</section></div></div>`,styles:[`
.unread{background:#008fa1;color:white;border-radius:20px;padding:2px 7px;float:left}.bulk{background:white;border:1px solid #dcebef;padding:18px;border-radius:16px;margin:12px 0}.bulk label{display:inline-flex;gap:8px;margin:10px}.bulk input[type=checkbox]{width:20px}.compose select{font:inherit;padding:8px;max-width:100%;margin:8px}.comms{color:#064660}.comms h1{font-size:24px}.comms h2{font-size:18px}.comms header p,small{color:#638195}.comms-grid{display:grid;grid-template-columns:280px minmax(0,1fr);gap:16px}.comms aside,.conversation{background:white;border:1px solid #dcebef;border-radius:18px;padding:18px;min-width:0}.comms button{font:inherit;cursor:pointer;border:1px solid #cde5eb;border-radius:10px;padding:10px 14px;color:#00697b;background:#f1fafb;min-height:44px}.comms button:disabled{opacity:.55;cursor:default}.comms input,.comms textarea{font:inherit;border:1px solid #cde5eb;border-radius:10px;padding:10px;width:100%;box-sizing:border-box;min-width:0}.search{display:flex;gap:6px;margin:8px 0 18px}.contact{display:block;text-align:start;width:100%;margin-bottom:8px}.contact small{display:block;margin-top:7px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.contact.selected{background:#dff3f5;border-color:#0095a5}.conversation header{display:flex;justify-content:space-between;align-items:center;gap:10px}.messages{display:flex;flex-direction:column;gap:12px;max-height:460px;overflow:auto;padding:16px 0;min-height:150px}.messages article{align-self:flex-start;background:#f4f7f9;border-radius:14px;padding:12px 16px;max-width:85%;overflow-wrap:anywhere}.messages article.mine{align-self:flex-end;background:#e0f5f2}.messages p{white-space:pre-wrap;margin:8px 0 0;line-height:1.8}.compose{border-top:1px solid #e5eef1;padding-top:15px}.compose textarea{margin-top:8px;resize:vertical}.compose div{display:flex;justify-content:space-between;align-items:center;margin-top:10px}.compose button{background:#008fa1;color:white}.error{color:#b62727}.empty{text-align:center;padding:50px 0}@media(max-width:700px){.comms-grid{grid-template-columns:1fr}.comms aside{max-height:230px;overflow:auto}.conversation header{flex-wrap:wrap}.messages{max-height:380px}}
`]})
export class FamilyMessages{
 private http=inject(HttpClient);private base=inject(HBH_CONFIG).apiBaseUrl+'/api/v1';private destroy=inject(DestroyRef);protected format=inject(FormatService);
 protected query=signal('');protected contacts=signal<Contact[]>([]);protected contactsLoading=signal(false);protected moreContacts=signal(false);protected selected=signal<Contact|null>(null);
 protected messages=signal<Message[]>([]);protected draft=signal('');protected error=signal('');protected sending=signal(false);protected loading=signal(false);protected more=signal(false);
 private version=0;private contactVersion=0;private drafts=new Map<number,string>();private attempt:{guardian:number;body:string;id:string}|null=null;
 protected canManage=(c:Contact)=>c.can_manage;
 protected bulk=signal(false);protected recipients=signal<number[]>([]);protected bulkBody=signal('');protected bulkStatus=signal('');private bulkAttempts=new Map<number,{body:string;id:string}>();
 protected templates=[{title:'تذكير بالموعد',body:'مرحبًا، نرجو مراجعة موعد طفلكم القادم في قسم المواعيد بالبوابة وتأكيد الحضور. شكرًا لتعاونكم.'},{title:'تقرير جديد',body:'مرحبًا، يمكنكم الاطلاع على التقارير المتاحة لطفلكم من قسم التقارير بالبوابة.'},{title:'التواصل مع المركز',body:'مرحبًا، يرجى التواصل مع فريق المركز بخصوص متابعة طفلكم. يسعدنا مساعدتكم.'}];
 protected useTemplate(body:string){if(body)this.draft.set((this.draft()?this.draft()+'\n':'')+body);}
 protected toggleRecipient(id:number){this.recipients.update(ids=>ids.includes(id)?ids.filter(v=>v!==id):[...ids,id]);}
 protected sendBulk(){const body=this.bulkBody().trim(),ids=this.recipients();if(!body||!ids.length||this.sending()||!this.contacts().some(this.canManage))return;this.sending.set(true);this.bulkStatus.set('جارٍ الإرسال…');
 forkJoin(ids.map(id=>{let attempt=this.bulkAttempts.get(id);if(!attempt||attempt.body!==body){attempt={body,id:crypto.randomUUID()};this.bulkAttempts.set(id,attempt)}return this.http.post(this.base+'/family-messages/'+id,{body,request_id:attempt.id}).pipe(map(()=>({id,ok:true})),catchError(()=>of({id,ok:false})))})).pipe(takeUntilDestroyed(this.destroy)).subscribe(results=>{const failed=results.filter(r=>!r.ok).map(r=>r.id);for(const r of results)if(r.ok)this.bulkAttempts.delete(r.id);this.recipients.set(failed);this.sending.set(false);this.bulkStatus.set('تم الإرسال إلى '+(results.length-failed.length)+' أسرة.'+(failed.length?' تعذر تأكيد '+failed.length+' رسائل؛ أعد المحاولة للأسر المتبقية.':''));if(!failed.length)this.bulkBody.set('');this.search(true)});
 }
 constructor(){this.search();interval(15000).pipe(takeUntilDestroyed(this.destroy)).subscribe(()=>{if(document.visibilityState==='visible'&&!this.loading()&&!this.sending()&&!this.contactsLoading()){this.search(true);if(this.selected()&&!this.more())this.load(false,true)}})}
 protected search(quiet=false){const version=++this.contactVersion;if(!quiet){this.contactsLoading.set(true);this.error.set('');}this.http.get<{rows:Contact[];more:boolean}>(this.base+'/family-contacts',{params:new HttpParams().set('q',this.query().trim())}).pipe(takeUntilDestroyed(this.destroy)).subscribe({next:r=>{if(version!==this.contactVersion)return;this.contacts.set(r.rows);this.moreContacts.set(r.more);this.contactsLoading.set(false);if(!this.selected() && r.rows.length===1)this.select(r.rows[0])},error:()=>{if(version!==this.contactVersion)return;this.contactsLoading.set(false);this.error.set('تعذر تحميل الأسر. حاول البحث مرة أخرى.')}})}
 protected select(contact:Contact){if(this.sending())return;const previous=this.selected();if(previous)this.drafts.set(previous.guardian_id,this.draft());this.selected.set(contact);this.draft.set(this.drafts.get(contact.guardian_id)??'');this.messages.set([]);this.more.set(false);this.load()}
 protected load(older=false,quiet=false){const contact=this.selected();if(!contact)return;const version=++this.version;if(!quiet){this.loading.set(true);this.error.set('');}let params=new HttpParams();if(older&&this.messages().length)params=params.set('before',this.messages()[0].message_id);
 this.http.get<{rows:Message[];more:boolean}>(this.base+'/family-messages/'+contact.guardian_id,{params}).pipe(takeUntilDestroyed(this.destroy)).subscribe({next:r=>{if(version!==this.version)return;const rows=[...r.rows].reverse();this.messages.set(older?[...rows,...this.messages()]:rows);this.more.set(r.more);this.loading.set(false);if(!older&&rows.length&&document.visibilityState==='visible')this.http.post(this.base+'/family-messages/'+contact.guardian_id+'/read',{message_id:rows[rows.length-1].message_id}).pipe(takeUntilDestroyed(this.destroy)).subscribe({next:()=>this.contacts.update(cs=>cs.map(c=>c.guardian_id===contact.guardian_id?{...c,unread:0}:c)),error:()=>{}})},error:()=>{if(version!==this.version)return;this.loading.set(false);this.error.set('تعذر تحميل الرسائل. اضغط تحديث الرسائل.')}})}
 protected send(){const contact=this.selected(),body=this.draft().trim();if(!contact?.can_send||!body||this.sending())return;if(!this.attempt||this.attempt.body!==body||this.attempt.guardian!==contact.guardian_id)this.attempt={guardian:contact.guardian_id,body,id:crypto.randomUUID()};this.sending.set(true);this.error.set('');this.http.post(this.base+'/family-messages/'+contact.guardian_id,{body,request_id:this.attempt.id}).pipe(takeUntilDestroyed(this.destroy)).subscribe({next:()=>{this.sending.set(false);this.draft.set('');this.drafts.delete(contact.guardian_id);this.attempt=null;this.load()},error:()=>{this.sending.set(false);this.error.set('تعذر تأكيد الإرسال. الرسالة محفوظة هنا ويمكن إعادة المحاولة.')}})}
}
