#!/usr/bin/env bash
# Copy the design system out of html/ into the Angular portal.
#
# html/ is the source. The files under web/portal/src/styles and
# web/portal/src/assets/brand are copies, and editing a copy is how two
# versions of the same stylesheet start disagreeing. Edit html/, run this.
#
# No `for f in $(ls ...)`: this project lives under a path with a space in it,
# and word splitting kills the loop on two directories that do not exist.
set -euo pipefail
cd "$(dirname "$0")/.."

ROOT="$PWD"
SRC_STYLES="$ROOT/html"
SRC_SPRITE="$ROOT/html/parts/hbh-icons-sprite.html"
DST_STYLES="$ROOT/web/portal/src/styles"
DST_OPS_STYLES="$ROOT/web/ops/src/styles"
DST_BRAND="$ROOT/web/portal/src/assets/brand"
DST_OPS_BRAND="$ROOT/web/ops/src/assets/brand"
DST_SPRITE="$ROOT/web/shared/src/sprite/icon-sprite.html"

styles=(hbh-shared.css hbh-parent.css)
app_styles=(app/hbh-app.css)
ops_styles=(hbh-shared.css hbh-admin.css hbh-screens.css)
brand=(hbh-logo-mark.png hbh-logo-wordmark.png)

mkdir -p "$DST_STYLES" "$DST_BRAND" "$DST_OPS_STYLES" "$DST_OPS_BRAND"

copied=0

for name in "${styles[@]}"; do
  cp -- "$SRC_STYLES/$name" "$DST_STYLES/$name"
  copied=$((copied + 1))
done

for name in "${app_styles[@]}"; do
  cp -- "$SRC_STYLES/$name" "$DST_STYLES/$(basename -- "$name")"
  copied=$((copied + 1))
done

for name in "${brand[@]}"; do
  cp -- "$SRC_STYLES/$name" "$DST_BRAND/$name"
  copied=$((copied + 1))
done

# The sprite becomes a component template. Its Arabic header comment is
# replaced by one that says where the file came from.
{
  printf '%s\n' '<!-- Single source for every icon in the portal. Rendered once at the app'
  printf '%s\n' '     root; every <hbh-icon> references a symbol from here by id.'
  printf '%s\n' '     Generated by scripts/sync-design.sh from html/parts/hbh-icons-sprite.html'
  printf '%s\n' '     - do not edit this copy. -->'
  sed -n '6,$p' -- "$SRC_SPRITE"
} > "$DST_SPRITE"
copied=$((copied + 1))

echo "synced $copied design files into web/portal"

for name in "${ops_styles[@]}"; do
  cp -- "$SRC_STYLES/$name" "$DST_OPS_STYLES/$name"
  copied=$((copied + 1))
done

for name in "${brand[@]}"; do
  cp -- "$SRC_STYLES/$name" "$DST_OPS_BRAND/$name"
done

# portal.css and ops.css are NOT synced: each is its app's own layer over the
# system, and it has no counterpart in html/.
